language: node_js
node_js:
  - $NODE_VERSION
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
before_install:
  # native dependencies
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo apt-get update -qq;
      sudo apt-get install -qq libxml2-dev;
      sudo apt-get install -qq libappindicator1;
    fi
install:
  - git config --global core.autocrlf input
  - git reset --hard HEAD
  - npm run sencha:clean
  - git clone https://github.com/saenzramiro/rambox-build.git $TRAVIS_BUILD_DIR/build/production/Rambox/
  - npm install
  - npm uninstall electron-prebuilt
  - npm i electron-prebuilt@$ELECTRON
  - npm --prefix $TRAVIS_BUILD_DIR/build/production/Rambox/ install $TRAVIS_BUILD_DIR/build/production/Rambox/
script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - npm run build:$TRAVIS_OS_NAME
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
      - if [ $TRAVIS_OS_NAME == "linux" ]; then
          - "dist/rambox-0.4.1.1-ia32.zip"
          - "dist/rambox-0.4.1.1.zip"
          - "dist/rambox-0.4.1.1-ia32.deb"
          - "dist/rambox-0.4.1.1.deb"
          - "dist/rambox-0.4.1.1-ia32.tar.gz"
          - "dist/rambox-0.4.1.1.tar.gz"
          - "dist/Rambox-0.4.1.1-ia32.AppImage"
          - "dist/Rambox-0.4.1.1.AppImage"
        fi
      - if [ $TRAVIS_OS_NAME == "osx" ]; then
          - "dist/mac/Rambox-0.4.1.1-mac.zip"
          - "dist/mac/Rambox-0.4.1.1.dmg"
        fi
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0f214eb0d0017d3c5561
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
